-- Rodinná kuchárka v1.2 – spustite JEDENKRÁT v Supabase SQL Editore.

alter table public.recipes add column if not exists updated_at timestamptz;
alter table public.recipes add column if not exists updated_by uuid references auth.users(id);

create table if not exists public.recipe_history (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  changed_by uuid references auth.users(id),
  changed_by_name text,
  change_note text,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recipe_comments (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text,
  comment_text text not null check (char_length(trim(comment_text)) > 0),
  created_at timestamptz not null default now()
);

alter table public.recipe_history enable row level security;
alter table public.recipe_comments enable row level security;

drop policy if exists "history_read_authenticated" on public.recipe_history;
create policy "history_read_authenticated" on public.recipe_history
for select to authenticated using (true);

drop policy if exists "history_insert_authenticated" on public.recipe_history;
create policy "history_insert_authenticated" on public.recipe_history
for insert to authenticated with check (changed_by = auth.uid());

drop policy if exists "comments_read_authenticated" on public.recipe_comments;
create policy "comments_read_authenticated" on public.recipe_comments
for select to authenticated using (true);

drop policy if exists "comments_insert_own" on public.recipe_comments;
create policy "comments_insert_own" on public.recipe_comments
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "comments_delete_own_or_admin" on public.recipe_comments;
create policy "comments_delete_own_or_admin" on public.recipe_comments
for delete to authenticated using (
  user_id = auth.uid() or exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  )
);

do $$ begin
  alter publication supabase_realtime add table public.recipe_comments;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.recipe_history;
exception when duplicate_object then null; end $$;
